version: '3'

services:
  app:
    image: necdet/table-data-dashboard
    build:
      context: ../
      dockerfile: ./.docker/app/Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - WEB_USERNAME=${WEB_USERNAME}
      - WEB_PASSWORD=${WEB_PASSWORD}
      - WEB_SERVER_PORT=${WEB_SERVER_PORT}
      - DATA_FOLDER_PATH=${DATA_FOLDER_PATH}
    ports:
      - ${WEB_SERVER_PORT}:${WEB_SERVER_PORT}
    networks:
      - test-network
    depends_on:
      - mysql_db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql_db", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}" ]
      interval: 5s
      timeout: 3s
      retries: 5

  mysql_db:
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/backup:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306
    networks:
      - test-network

networks:
  test-network:
      driver: bridge
